foo

diff --git a/.github/workflows/pr-database.yml b/.github/workflows/pr-database.yml
--- a/.github/workflows/pr-database.yml
+++ b/.github/workflows/pr-database.yml
@@ -42,5 +42,19 @@ jobs:
         shell: bash
       - run: ./ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
         shell: bash
-      - run: timeout 1h ./ngrok http 5555
+      - run: |
+          timeout 1h ./ngrok http 5555 --log ".ngrok.log" &
+
+          sleep 10
+          HAS_ERRORS=$(grep "command failed" < .ngrok.log)
+
+          if [[ -z "$HAS_ERRORS" ]]; then
+            echo ""
+            echo "=========================================="
+            echo "$(cat .ngrok.log)"
+            echo "=========================================="
+          else
+            echo "$HAS_ERRORS"
+            exit 4
+          fi
         shell: bash
